

	.FUNCT	RT-RM-ICE-ROOM:ANY:0:1,CONTEXT
	EQUAL?	CONTEXT,M-F-LOOK,M-V-LOOK,M-LOOK \?CCL3
	EQUAL?	CONTEXT,M-LOOK \?CCL6
	PRINTI	"You are"
	ICALL1	RT-STANDING-MSG
	PRINTI	" in"
	JUMP	?CND4
?CCL6:	PRINTI	"The tunnel broadens out to"
?CND4:	PRINTI	" a frigid room whose walls are lined with ice. It is so cold that your breath freezes as soon as it comes out of your mouth - whereupon it falls to the ground and shatters.
"
	RFALSE	
?CCL3:	EQUAL?	CONTEXT,M-BEG \?CCL8
	EQUAL?	PRSA,V?YELL,V?GOODBYE /?CCL11
	EQUAL?	PRSA,V?HELLO,V?$PASSWORD,V?SAY \FALSE
?CCL11:	IN?	TH-ICE,RM-ICE-ROOM \?CND14
	FSET?	TH-ICE,FL-TOUCHED /?CND14
	FCLEAR	TH-ICE,FL-SEEN
	FCLEAR	TH-ICE,FL-TOUCHED
	REMOVE	TH-ICE
	ICALL2	RT-DEQUEUE,RT-I-ICE-FALL
	ICALL	RT-PRINT-OBJ,TH-ICE,K-ART-THE,TRUE-VALUE
	PRINT	K-ICE-FALL-MSG
	CRLF	
	CRLF	
?CND14:	DIROUT	D-TABLE-ON,GL-ICE-TEXT
	EQUAL?	PRSA,V?$PASSWORD \?CCL20
	PRINTI	"nudd"
	JUMP	?CND18
?CCL20:	EQUAL?	PRSA,V?HELLO \?CCL22
	PRINTI	"hello"
	JUMP	?CND18
?CCL22:	EQUAL?	PRSA,V?GOODBYE \?CCL24
	PRINTI	"goodbye"
	JUMP	?CND18
?CCL24:	EQUAL?	PRSA,V?YELL \?CCL26
	PRINTI	"AAAaaaarrrrrrrrrgh"
	JUMP	?CND18
?CCL26:	EQUAL?	INTQUOTE,PRSO,PRSI \?CCL28
	ICALL1	PRINT-INTQUOTE
	JUMP	?CND18
?CCL28:	EQUAL?	PRSA,V?SAY \?CND18
	ICALL2	NP-PRINT,PRSO-NP
?CND18:	DIROUT	D-TABLE-OFF
	MOVE	TH-ICE,RM-ICE-ROOM
	ADD	GL-MOVES,1
	ICALL	RT-QUEUE,RT-I-ICE-FALL,STACK
	SET	'GL-ICE-TEMP,0
	PRINTI	"The words freeze into a block of ice as soon as they come out of your mouth. It hangs in the air for a second before it starts to fall.
"
	BOR	GL-UPDATE-WINDOW,K-UPD-OBJS >GL-UPDATE-WINDOW
	EQUAL?	GL-WINDOW-TYPE,K-WIN-DESC \TRUE
	ICALL1	RT-UPDATE-DESC-WINDOW
	RTRUE	
?CCL8:	EQUAL?	CONTEXT,M-ENTER \?CCL33
	SET	'GL-PICTURE-NUM,K-PIC-ICE-ROOM
	EQUAL?	GL-WINDOW-TYPE,K-WIN-PICT \FALSE
	ICALL1	RT-UPDATE-PICT-WINDOW
	RFALSE	
?CCL33:	EQUAL?	CONTEXT,M-ENTERED \?CCL37
	CALL2	RT-IS-QUEUED?,RT-I-TEMP
	ZERO?	STACK \FALSE
	ICALL	RT-QUEUE,RT-I-TEMP,GL-MOVES
	RFALSE	
?CCL37:	EQUAL?	CONTEXT,M-EXIT \?CCL41
	CALL	RT-META-IN?,TH-ICE,CH-PLAYER
	ZERO?	STACK /?CCL44
	ICALL	RT-QUEUE,RT-I-ICE-MELT,GL-MOVES
	RFALSE	
?CCL44:	CALL	RT-META-IN?,TH-ICE,RM-ICE-ROOM
	ZERO?	STACK /FALSE
	REMOVE	TH-ICE
	RFALSE	
?CCL41:	ZERO?	CONTEXT \FALSE
	RFALSE	


	.FUNCT	RT-PS-ICE:ANY:0:3,CONTEXT,ART,CAP?
	EQUAL?	CONTEXT,M-OBJDESC \?CCL3
	FCLEAR	PSEUDO-OBJECT,FL-PLURAL
	FSET	PSEUDO-OBJECT,FL-VOWEL
	ZERO?	ART /?CND4
	ICALL	PRINT-ARTICLE,PSEUDO-OBJECT,ART,CAP?
?CND4:	EQUAL?	ART,FALSE-VALUE,K-ART-THE,K-ART-A /?CCL8
	EQUAL?	ART,K-ART-ANY \FALSE
?CCL8:	ZERO?	ART /?CND11
	PRINTC	32
?CND11:	PRINTI	"ice"
	RTRUE	
?CCL3:	ZERO?	CONTEXT \FALSE
	EQUAL?	PRSA,V?EXAMINE \?CCL16
	PRINTR	"The stalagmites and stalactites are made of solid ice."
?CCL16:	EQUAL?	PRSA,V?EAT \?CCL18
	PRINT	K-EAT-ICE-MSG
	CRLF	
	RTRUE	
?CCL18:	CALL1	TOUCH-VERB?
	ZERO?	STACK /FALSE
	PRINTR	"The rock-solid ice remains unaffected by your actions."


	.FUNCT	RT-TH-ICE:ANY:0:1,CONTEXT
	ZERO?	CONTEXT \FALSE
	EQUAL?	PRSA,V?TAKE \?CCL5
	FSET?	TH-ICE,FL-TOUCHED /?CCL5
	CALL2	RT-DO-TAKE,TH-ICE
	ZERO?	STACK /TRUE
	PRINTR	"You catch the block of ice before it hits the ground."
?CCL5:	EQUAL?	PRSA,V?EAT \FALSE
	PRINT	K-EAT-ICE-MSG
	CRLF	
	RTRUE	


	.FUNCT	RT-I-ICE-FALL:ANY:0:0
	IN?	TH-ICE,RM-ICE-ROOM \FALSE
	FSET?	TH-ICE,FL-TOUCHED /FALSE
	FCLEAR	TH-ICE,FL-SEEN
	FCLEAR	TH-ICE,FL-TOUCHED
	REMOVE	TH-ICE
	EQUAL?	HERE,RM-ICE-ROOM \FALSE
	CRLF	
	ICALL	RT-PRINT-OBJ,TH-ICE,K-ART-THE,TRUE-VALUE
	PRINT	K-ICE-FALL-MSG
	CRLF	
	BOR	GL-UPDATE-WINDOW,K-UPD-OBJS >GL-UPDATE-WINDOW
	EQUAL?	GL-WINDOW-TYPE,K-WIN-DESC \TRUE
	ICALL1	RT-UPDATE-DESC-WINDOW
	RTRUE	


	.FUNCT	RT-I-ICE-MELT:ANY:0:0,H,L,?TMP1
	INC	'GL-ICE-TEMP
	CALL	RT-META-IN?,TH-ICE,HERE >H
	LOC	TH-ICE >L
	ZERO?	H /?CCL3
	EQUAL?	HERE,RM-ICE-ROOM \?CCL3
	SET	'GL-ICE-TEMP,0
	CRLF	
	ICALL	RT-PRINT-OBJ,TH-ICE,K-ART-THE,TRUE-VALUE
	PRINTR	" refreezes in the cold air."
?CCL3:	EQUAL?	GL-ICE-TEMP,3 \?CCL7
	ZERO?	H /?CND1
	CRLF	
	CALL2	ACCESSIBLE?,TH-ICE
	ZERO?	STACK /?CCL12
	ICALL	RT-PRINT-OBJ,TH-ICE,K-ART-THE,TRUE-VALUE
	PRINTI	" melts completely and, """
	ADD	GL-ICE-TEXT,2 >?TMP1
	GET	GL-ICE-TEXT,0
	PRINTT	?TMP1,STACK
	PRINTI	""" rings out loud and clear."
	EQUAL?	HERE,RM-HOT-ROOM \?CCL15
	GET	GL-ICE-TEXT,0
	EQUAL?	STACK,4 \?CCL15
	GETB	GL-ICE-TEXT,2
	EQUAL?	STACK,110,78 \?CCL15
	GETB	GL-ICE-TEXT,3
	EQUAL?	STACK,117,85 \?CCL15
	GETB	GL-ICE-TEXT,4
	EQUAL?	STACK,100,68 \?CCL15
	GETB	GL-ICE-TEXT,5
	EQUAL?	STACK,100,68 \?CCL15
	PRINTI	" The face in the door smiles and says, ""Yes. That's it. Very good. Now you may enter.""

The door swings open and you walk through. It closes behind you with an ominous ""clank.""

"
	ICALL	RT-GOTO,RM-DEMON-HALL,TRUE-VALUE
	JUMP	?CND10
?CCL15:	CRLF	
	JUMP	?CND10
?CCL12:	PRINTI	"You hear a muffled voice from within"
	LOC	TH-ICE
	ICALL	RT-PRINT-OBJ,STACK,K-ART-THE
	PRINTI	". It sounded like """
	ADD	GL-ICE-TEXT,2 >?TMP1
	GET	GL-ICE-TEXT,0
	PRINTT	?TMP1,STACK
	PRINTI	"."""
	CRLF	
?CND10:	EQUAL?	L,CH-PLAYER \?CCL24
	BOR	GL-UPDATE-WINDOW,K-UPD-INVT >GL-UPDATE-WINDOW
	EQUAL?	GL-WINDOW-TYPE,K-WIN-INVT \?CND22
	ICALL1	RT-UPDATE-INVT-WINDOW
	JUMP	?CND22
?CCL24:	ZERO?	H /?CND22
	CALL2	VISIBLE?,TH-ICE
	ZERO?	STACK /?CND22
	EQUAL?	L,HERE /?CCL31
	FSET?	L,FL-SURFACE /?CCL31
	FSET?	L,FL-TRANSPARENT \?CND22
?CCL31:	BOR	GL-UPDATE-WINDOW,K-UPD-OBJS >GL-UPDATE-WINDOW
	EQUAL?	GL-WINDOW-TYPE,K-WIN-DESC \?CND22
	ICALL1	RT-UPDATE-DESC-WINDOW
?CND22:	REMOVE	TH-ICE
	RTRUE	
?CCL7:	ADD	GL-MOVES,1
	ICALL	RT-QUEUE,RT-I-ICE-MELT,STACK
?CND1:	ZERO?	H /FALSE
	CALL2	VISIBLE?,TH-ICE
	ZERO?	STACK /FALSE
	EQUAL?	GL-ICE-TEMP,1 \?CCL43
	LOC	TH-ICE >L
	EQUAL?	L,CH-PLAYER \?CND44
	SET	'L,TH-HANDS
?CND44:	PRINTI	"
The block of ice"
	ICALL2	RT-IN-ON-MSG,L
	ICALL	RT-PRINT-OBJ,L,K-ART-THE
	PRINTR	" begins to melt."
?CCL43:	EQUAL?	GL-ICE-TEMP,2 \FALSE
	PRINTR	"
The block is rapidly shrinking."


	.FUNCT	RT-I-TEMP:ANY:0:0,DOWN?
	EQUAL?	HERE,RM-ICE-ROOM \?CCL3
	SET	'DOWN?,TRUE-VALUE
	GRTR?	GL-TEMP,0 \?CCL6
	SET	'GL-TEMP,-1
	JUMP	?CND1
?CCL6:	DEC	'GL-TEMP
	JUMP	?CND1
?CCL3:	EQUAL?	HERE,RM-HOT-ROOM \?CCL8
	INC	'GL-TEMP
	JUMP	?CND1
?CCL8:	GRTR?	GL-TEMP,0 \?CCL10
	SET	'DOWN?,TRUE-VALUE
	DEC	'GL-TEMP
	JUMP	?CND1
?CCL10:	LESS?	GL-TEMP,0 \FALSE
	INC	'GL-TEMP
?CND1:	ZERO?	GL-TEMP \?CCL14
	EQUAL?	HERE,RM-ICE-ROOM,RM-HOT-ROOM \?CND13
?CCL14:	ADD	GL-MOVES,1
	ICALL	RT-QUEUE,RT-I-TEMP,STACK
?CND13:	CRLF	
	EQUAL?	GL-TEMP,4 \?CCL19
	PRINTI	"You pass out from the heat and die.
"
	CALL1	RT-END-OF-GAME
	RSTACK	
?CCL19:	EQUAL?	GL-TEMP,-4 \?CCL21
	PRINTI	"The cold finally overpowers you and you freeze to death.
"
	CALL1	RT-END-OF-GAME
	RSTACK	
?CCL21:	EQUAL?	GL-TEMP,3,-3 \?CCL23
	PRINTI	"You won't last much longer in this "
	LESS?	GL-TEMP,0 \?CCL26
	PRINTI	"cold"
	JUMP	?CND24
?CCL26:	PRINTI	"heat"
?CND24:	PRINTR	"."
?CCL23:	EQUAL?	GL-TEMP,2 \?CCL28
	PRINTI	"Your blood is beginning to "
	ZERO?	DOWN? /?CCL31
	PRINTI	"cool"
	JUMP	?CND29
?CCL31:	PRINTI	"boil"
?CND29:	PRINTR	"."
?CCL28:	EQUAL?	GL-TEMP,-2 \?CCL33
	ZERO?	DOWN? /?CCL36
	PRINTR	"Your blood is starting to slow down."
?CCL36:	PRINTR	"You're beginning to thaw out."
?CCL33:	EQUAL?	GL-TEMP,1 \?CCL38
	ZERO?	DOWN? /?CCL41
	PRINTR	"You're feeling much cooler."
?CCL41:	PRINTR	"The heat begins to make you sweat."
?CCL38:	EQUAL?	GL-TEMP,-1 \?CCL43
	ZERO?	DOWN? /?CCL46
	PRINTR	"The cold begins to creep into your bones."
?CCL46:	PRINTR	"Your blood is warming up."
?CCL43:	ZERO?	GL-TEMP \FALSE
	PRINTR	"Your body temperature returns to normal."


	.FUNCT	RT-RM-HOT-ROOM:ANY:0:1,CONTEXT
	EQUAL?	CONTEXT,M-F-LOOK,M-V-LOOK,M-LOOK \?CCL3
	PRINTI	"You "
	EQUAL?	CONTEXT,M-LOOK \?CCL6
	PRINTI	"are"
	ICALL1	RT-STANDING-MSG
	PRINTI	" in"
	JUMP	?CND4
?CCL6:	EQUAL?	CONTEXT,M-F-LOOK /?CND7
	PRINTI	"re"
?CND7:	PRINTI	"enter"
?CND4:	PRINTI	" a room that is unbearably hot. There is a closed door directly to the north. The door has a face in it.
"
	EQUAL?	CONTEXT,M-F-LOOK \FALSE
	PRINTI	"
The face smiles at you for a moment and then says, ""Welcome to the Hall of the Demon. Entry to the hall is simple. All you have to do is tell me the password. I'll even make it simple for you. The password is the name of the demon who rules within. I'll even tell you his name. It's Nudd.""

All the while he speaks, you get hotter and hotter. You begin to feel very uncomfortable, and your throat becomes parched and dry.
"
	RFALSE	
?CCL3:	EQUAL?	CONTEXT,M-BEG \?CCL12
	EQUAL?	PRSA,V?TELL \?CCL15
	ZERO?	P-CONT \FALSE
?CCL15:	CALL1	SPEAKING-VERB?
	ZERO?	STACK /FALSE
	PRINT	K-DRY-THROAT-MSG
	CRLF	
	RTRUE	
?CCL12:	EQUAL?	CONTEXT,M-ENTER \?CCL21
	SET	'GL-PICTURE-NUM,K-PIC-HOT-ROOM
	EQUAL?	GL-WINDOW-TYPE,K-WIN-PICT \?CND22
	ICALL1	RT-UPDATE-PICT-WINDOW
?CND22:	CALL2	RT-IS-QUEUED?,RT-I-TEMP
	ZERO?	STACK \?CND24
	ICALL	RT-QUEUE,RT-I-TEMP,GL-MOVES
?CND24:	FSET?	LG-HOT-DOOR,FL-OPEN \FALSE
	FCLEAR	LG-HOT-DOOR,FL-OPEN
	RFALSE	
?CCL21:	EQUAL?	CONTEXT,M-EXIT \?CCL29
	FCLEAR	LG-HOT-DOOR,FL-OPEN
	RFALSE	
?CCL29:	ZERO?	CONTEXT \FALSE
	RFALSE	


	.FUNCT	RT-LG-HOT-DOOR:ANY:0:1,CONTEXT
	EQUAL?	CONTEXT,M-WINNER \?CCL3
	EQUAL?	HERE,RM-HOT-ROOM \?CCL6
	PRINT	K-DRY-THROAT-MSG
	CRLF	
	RTRUE	
?CCL6:	ICALL	RT-PRINT-OBJ,LG-HOT-DOOR,K-ART-THE,TRUE-VALUE,STR?80
	PRINTR	"n't respond."
?CCL3:	ZERO?	CONTEXT \FALSE
	EQUAL?	HERE,RM-HOT-ROOM \?CCL10
	CALL1	TOUCH-VERB?
	ZERO?	STACK /?CCL13
	PRINTR	"You edge nearer the door, but it radiates such intense heat that you pull back."
?CCL13:	EQUAL?	PRSA,V?EXAMINE \FALSE
	CALL	NOUN-USED?,LG-HOT-DOOR,W?FACE
	ZERO?	STACK /?CCL18
	PRINTR	"It looks like an honest, friendly face."
?CCL18:	PRINTR	"The door glows with intense heat."
?CCL10:	EQUAL?	HERE,RM-DEMON-HALL \FALSE
	CALL	NOUN-USED?,LG-HOT-DOOR,W?FACE
	ZERO?	STACK /?CCL23
	CALL1	NP-CANT-SEE
	RSTACK	
?CCL23:	EQUAL?	PRSA,V?OPEN \?CCL25
	FSET?	CH-DEMON,FL-LOCKED /FALSE
	FSET?	CH-DEMON,FL-BROKEN /FALSE
	PRINTI	"""Traitor!"" shrieks the demon. A thunderbolt of electricity streaks across the room and kills you where you stand.
"
	CALL1	RT-END-OF-GAME
	RSTACK	
?CCL25:	EQUAL?	PRSA,V?EXAMINE \FALSE
	PRINTR	"From this side, the door doesn't look hot at all."

	.ENDI
