

	.FUNCT	RT-RM-TOWN-SQUARE:ANY:0:1,CONTEXT,OBJ1,OBJ2,N
	EQUAL?	CONTEXT,M-ENTER \?CCL3
	SET	'GL-PICTURE-NUM,K-PIC-TOWN-SQUARE
	EQUAL?	GL-WINDOW-TYPE,K-WIN-PICT \?CND4
	ICALL1	RT-UPDATE-PICT-WINDOW
?CND4:	IN?	TH-ARMOUR,CH-I-KNIGHT \?CCL8
	SET	'OBJ1,TH-ARMOUR
	JUMP	?CND6
?CCL8:	IN?	TH-SHIELD,CH-I-KNIGHT \?CCL10
	SET	'OBJ1,TH-SHIELD
	JUMP	?CND6
?CCL10:	IN?	TH-PUMICE,CH-I-KNIGHT \?CCL12
	SET	'OBJ1,TH-PUMICE
	JUMP	?CND6
?CCL12:	IN?	TH-IVORY-KEY,CH-I-KNIGHT \?CND6
	SET	'OBJ1,TH-IVORY-KEY
?CND6:	ZERO?	OBJ1 /FALSE
	IN?	TH-ARMOUR,CH-IDIOT \?CCL18
	SET	'OBJ2,TH-ARMOUR
	JUMP	?CND16
?CCL18:	IN?	TH-SHIELD,CH-IDIOT \?CCL20
	SET	'OBJ2,TH-SHIELD
	JUMP	?CND16
?CCL20:	IN?	TH-PUMICE,CH-IDIOT \?CCL22
	SET	'OBJ2,TH-PUMICE
	JUMP	?CND16
?CCL22:	IN?	TH-IVORY-KEY,CH-IDIOT \?CND16
	SET	'OBJ2,TH-IVORY-KEY
?CND16:	ZERO?	OBJ2 /?CND24
	ICALL	RT-IDIOT-GIVE,OBJ2,CH-I-KNIGHT
?CND24:	ICALL2	RT-IDIOT-TAKE,OBJ1
	FSET	CH-I-KNIGHT,FL-BROKEN
	RFALSE	
?CCL3:	EQUAL?	CONTEXT,M-ENTERED \?CCL27
	CALL	RT-QUEUE,RT-I-IDIOT-MSG,GL-MOVES
	RSTACK	
?CCL27:	EQUAL?	CONTEXT,M-EXIT \?CCL29
	ICALL2	RT-DEQUEUE,RT-I-IDIOT-MSG
	RFALSE	
?CCL29:	EQUAL?	CONTEXT,M-BEG \?CCL31
	CALL2	RT-IS-QUEUED?,RT-I-IDIOT-MSG
	ZERO?	STACK \?CND32
	ICALL	RT-QUEUE,RT-I-IDIOT-MSG,GL-MOVES
?CND32:	SET	'GL-IDIOT-MSG,TRUE-VALUE
	RFALSE	
?CCL31:	EQUAL?	CONTEXT,M-F-LOOK,M-V-LOOK,M-LOOK \?CCL35
	EQUAL?	CONTEXT,M-LOOK \?CCL38
	ICALL	RT-PRINT-OBJ,WINNER,K-ART-THE,TRUE-VALUE,STR?69
	ICALL1	RT-STANDING-MSG
	PRINTI	" in"
	JUMP	?CND36
?CCL38:	ICALL	RT-PRINT-OBJ,WINNER,K-ART-THE,TRUE-VALUE
	ICALL1	RT-WALK-MSG
	PRINTI	" into"
?CND36:	FSET	LG-CASTLE,FL-SEEN
	FSET	RM-TAVERN,FL-SEEN
	FSET	RM-VILLAGE-GREEN,FL-SEEN
	FSET	CH-IDIOT,FL-SEEN
	ICALL2	THIS-IS-IT,CH-IDIOT
	PRINTI	" the town square. The churchyard lies to the north, and the castle to the east. To your south you see the entrance to the town's only tavern, and to the west is the village green.

The village idiot is here, idly playing with"
	ICALL1	RT-IDIOT-PLAY-MSG
	EQUAL?	CONTEXT,M-F-LOOK,M-V-LOOK /?CTR40
	EQUAL?	PRSA,V?LOOK \?CCL41
?CTR40:	CALL2	RT-I-IDIOT-MSG,TRUE-VALUE
	ZERO?	STACK \FALSE
	CRLF	
	RFALSE	
?CCL41:	CRLF	
	RFALSE	
?CCL35:	EQUAL?	CONTEXT,M-END \?CCL47
	EQUAL?	PRSA,V?TRANSFORM \FALSE
	EQUAL?	GL-PLAYER-FORM,GL-OLD-FORM /FALSE
	SET	'GL-IDIOT-MSG,FALSE-VALUE
	ICALL2	THIS-IS-IT,CH-IDIOT
	CRLF	
	ICALL	RT-PRINT-OBJ,CH-IDIOT,K-ART-THE,TRUE-VALUE
	PRINTR	" placidly accepts your transformation and drools on you."
?CCL47:	ZERO?	CONTEXT \FALSE
	RFALSE	


	.FUNCT	RT-CH-IDIOT:ANY:0:1,CONTEXT,OTHER,OBJ,N
	EQUAL?	CONTEXT,M-WINNER,FALSE-VALUE \?CCL3
	EQUAL?	PRSA,V?THANK,V?GOODBYE,V?HELLO \?CCL3
	EQUAL?	PRSA,V?HELLO \?CCL8
	SET	'GL-IDIOT-MSG,FALSE-VALUE
	PRINTR	"The idiot says brightly, ""Hello!"" and looks at you expectantly."
?CCL8:	EQUAL?	PRSA,V?GOODBYE \?CCL10
	SET	'GL-IDIOT-MSG,FALSE-VALUE
	PRINTR	"A cloud passes over the idiot's face. ""Goodbye,"" he says sadly."
?CCL10:	EQUAL?	PRSA,V?THANK \FALSE
	SET	'GL-IDIOT-MSG,FALSE-VALUE
	PRINTI	"The idiot smiles brightly and says, ""OK."""
	CRLF	
	FSET?	CH-PLAYER,FL-AIR /TRUE
	FSET	CH-PLAYER,FL-AIR
	ICALL	RT-SCORE-MSG,10,0,0,0
	RTRUE	
?CCL3:	EQUAL?	CONTEXT,M-WINNER \?CCL16
	CALL1	RT-IDIOT-WHISPERS-MSG
	RSTACK	
?CCL16:	EQUAL?	CONTEXT,M-CONT \?CCL18
	EQUAL?	PRSA,V?ASK-FOR \?CCL21
	EQUAL?	PRSO,CH-IDIOT \?CCL21
	ZERO?	NOW-PRSI /?CCL21
	SET	'GL-IDIOT-MSG,FALSE-VALUE
	PRINT	K-IDIOT-TRADE-MSG
	CRLF	
	RTRUE	
?CCL21:	EQUAL?	PRSA,V?ASK-ABOUT \?CCL26
	EQUAL?	PRSO,CH-IDIOT \?CCL26
	ZERO?	NOW-PRSI /?CCL26
	SET	'GL-IDIOT-MSG,FALSE-VALUE
	PRINTI	"""I got"
	ICALL	RT-PRINT-OBJ,PRSI,K-ART-HIM
	PRINTI	" from my Invisible Playmate,"" he says, giving"
	ICALL	RT-PRINT-OBJ,PRSI,K-ART-HIM
	PRINTI	" a little kick with his foot. "
	PRINT	K-IDIOT-TRADE-MSG
	CRLF	
	RTRUE	
?CCL26:	EQUAL?	PRSA,V?TRADE-FOR \?CCL31
	EQUAL?	PRSO,CH-IDIOT /FALSE
	ZERO?	NOW-PRSI /?CCL36
	CALL	RT-IDIOT-TRADE,PRSO,PRSI
	RSTACK	
?CCL36:	CALL	RT-IDIOT-TRADE,PRSI,PRSO
	RSTACK	
?CCL31:	CALL1	TOUCH-VERB?
	ZERO?	STACK /FALSE
	SET	'GL-IDIOT-MSG,FALSE-VALUE
	ICALL2	THIS-IS-IT,CH-IDIOT
	ICALL	RT-PRINT-OBJ,CH-IDIOT,K-ART-THE,TRUE-VALUE
	PRINTI	" smacks you on the head and says, ""Nasty"
	ICALL1	RT-FORM-MSG
	PRINTI	". Keep away from my "
	ZERO?	NOW-PRSI /?CCL41
	ICALL2	RT-PRINT-DESC,PRSI
	JUMP	?CND39
?CCL41:	ICALL2	RT-PRINT-DESC,PRSO
?CND39:	PRINTR	"."""
?CCL18:	ZERO?	CONTEXT \FALSE
	ZERO?	NOW-PRSI /?CCL45
	EQUAL?	PRSA,V?SHOW,V?TRADE-WITH,V?GIVE \FALSE
	CALL2	RT-IDIOT-TRADE,PRSO
	RSTACK	
?CCL45:	EQUAL?	PRSA,V?TELL \?CCL50
	ZERO?	P-CONT \FALSE
?CCL50:	EQUAL?	PRSA,V?EXAMINE \?CCL54
	FSET	CH-IDIOT,FL-SEEN
	PRINTI	"The idiot smiles back at you with a lopsided grin, and continues to play with"
	ICALL1	RT-IDIOT-PLAY-MSG
	CALL2	RT-I-IDIOT-MSG,TRUE-VALUE
	ZERO?	STACK \TRUE
	CRLF	
	RTRUE	
?CCL54:	EQUAL?	PRSA,V?LISTEN \?CCL58
	CALL1	RT-I-IDIOT-MSG
	RSTACK	
?CCL58:	CALL1	SPEAKING-VERB?
	ZERO?	STACK /?CCL60
	IN?	CH-IDIOT,HERE \?CCL60
	CALL1	RT-IDIOT-WHISPERS-MSG
	RSTACK	
?CCL60:	EQUAL?	PRSA,V?ASK-FOR \FALSE
	SET	'GL-IDIOT-MSG,FALSE-VALUE
	ICALL	RT-PRINT-OBJ,CH-IDIOT,K-ART-THE,TRUE-VALUE,STR?210
	PRINTI	" puzzled, and says, ""I'd give"
	ICALL	RT-PRINT-OBJ,PRSI,K-ART-HIM
	PRINTI	" to you, but I don't have"
	ICALL	RT-PRINT-OBJ,PRSI,K-ART-HIM
	PRINTR	"."""


	.FUNCT	RT-IDIOT-PLAY-MSG:ANY:0:0,N,OBJ,I,1ST?
	GET	K-IDIOT-OBJ-TBL,0 >N
	SET	'1ST?,TRUE-VALUE
?PRG1:	IGRTR?	'I,N /?REP2
	ZERO?	1ST? /?CCL8
	SET	'1ST?,FALSE-VALUE
	JUMP	?CND6
?CCL8:	EQUAL?	I,N /?PRD10
	PUSH	1
	JUMP	?PEN9
?PRD10:	PUSH	0
?PEN9:	ICALL2	RT-COMMA-MSG,STACK
?CND6:	GET	K-IDIOT-OBJ-TBL,I >OBJ
	ICALL	RT-PRINT-OBJ,OBJ,K-ART-A
	JUMP	?PRG1
?REP2:	PRINTI	" that lie"
	EQUAL?	N,1 \?CND12
	ZERO?	OBJ /?CND12
	FSET?	OBJ,FL-PLURAL \?CCL13
	FSET?	OBJ,FL-COLLECTIVE \?CND12
?CCL13:	PRINTC	115
?CND12:	PRINTI	" at his feet."
	RTRUE	


	.FUNCT	RT-IDIOT-WHISPERS-MSG:ANY:0:0
	SET	'GL-IDIOT-MSG,FALSE-VALUE
	PRINTI	"The idiot looks around to make sure no one is watching the two of you. Beckoning you to come closer, he whispers in your ear,"
	CALL2	RT-PICK-NEXT,K-IDIOT-MSG-TBL
	PRINT	STACK
	CRLF	
	RTRUE	


	.FUNCT	RT-I-IDIOT-MSG:ANY:0:1,SP?
	EQUAL?	HERE,RM-TOWN-SQUARE \FALSE
	EQUAL?	PRSA,V?WAIT \?CND1
	ZERO?	GL-IDIOT-WAIT \FALSE
?CND1:	FSET?	CH-PLAYER,FL-ASLEEP \?CCL9
	CALL2	RT-IS-QUEUED?,RT-I-SLEEP
	ADD	STACK,1
	ICALL	RT-QUEUE,RT-I-IDIOT-MSG,STACK
	RFALSE	
?CCL9:	ZERO?	GL-CLK-RUN /?CND7
	ADD	GL-MOVES,1
	ICALL	RT-QUEUE,RT-I-IDIOT-MSG,STACK
?CND7:	EQUAL?	PRSA,V?WAIT \?CCL13
	SET	'GL-IDIOT-WAIT,TRUE-VALUE
	ICALL2	THIS-IS-IT,CH-IDIOT
	PRINTI	"
While you wait,"
	ICALL	RT-PRINT-OBJ,CH-IDIOT,K-ART-THE
	PRINTI	" mumbles quietly to himself."
	CRLF	
	RFALSE	
?CCL13:	ZERO?	GL-IDIOT-MSG /FALSE
	SET	'GL-IDIOT-WAIT,FALSE-VALUE
	ICALL2	THIS-IS-IT,CH-IDIOT
	ZERO?	GL-CLK-RUN /?CCL18
	CRLF	
	ICALL	RT-PRINT-OBJ,CH-IDIOT,K-ART-THE,TRUE-VALUE
	JUMP	?CND16
?CCL18:	SET	'GL-IDIOT-MSG,FALSE-VALUE
	ZERO?	SP? /?CND19
	PRINTC	32
?CND19:	ICALL	RT-PRINT-OBJ,CH-IDIOT,K-ART-HE,TRUE-VALUE
?CND16:	PRINTI	" mumbles,"
	CALL2	RT-PICK-NEXT,K-IDIOT-MSG-TBL
	PRINT	STACK
	CRLF	
	RTRUE	


	.FUNCT	RT-IDIOT-TRADE:ANY:1:2,OBJ,ID
	ZERO?	ID \?CND1
	GET	K-IDIOT-OBJ-TBL,0
	RANDOM	STACK
	GET	K-IDIOT-OBJ-TBL,STACK >ID
?CND1:	EQUAL?	OBJ,ID \?CCL5
	SET	'GL-IDIOT-MSG,FALSE-VALUE
	ICALL	RT-PRINT-OBJ,CH-IDIOT,K-ART-THE,TRUE-VALUE
	PRINTI	" looks puzzled."
	CRLF	
	CALL2	RT-AUTHOR-MSG,STR?405
	RSTACK	
?CCL5:	IN?	OBJ,CH-IDIOT \?CCL7
	SET	'GL-IDIOT-MSG,FALSE-VALUE
	ICALL	RT-PRINT-OBJ,CH-IDIOT,K-ART-THE,TRUE-VALUE
	PRINTI	" carefully exchanges"
	ICALL	RT-PRINT-OBJ,OBJ,K-ART-THE
	PRINTI	" with"
	ICALL	RT-PRINT-OBJ,ID,K-ART-THE
	PRINTC	46
	CRLF	
	CALL2	RT-AUTHOR-MSG,STR?406
	RSTACK	
?CCL7:	FSET?	OBJ,FL-TAKEABLE /?CCL9
	SET	'GL-IDIOT-MSG,FALSE-VALUE
	ICALL	RT-PRINT-OBJ,CH-IDIOT,K-ART-THE,TRUE-VALUE
	PRINTI	" says, ""Hey, you can't trade"
	ICALL	RT-PRINT-OBJ,OBJ,K-ART-THE
	PRINTR	"."""
?CCL9:	CALL2	RT-NOT-HOLDING-MSG?,OBJ
	ZERO?	STACK \TRUE
	ICALL2	RT-IDIOT-GIVE,ID
	ICALL2	RT-IDIOT-TAKE,OBJ
	SET	'GL-IDIOT-MSG,FALSE-VALUE
	PRINTI	"""Oooh look! "
	ICALL	RT-PRINT-OBJ,OBJ,K-ART-A,TRUE-VALUE
	PRINTI	"!"" "
	ICALL	RT-PRINT-OBJ,CH-IDIOT,K-ART-THE,TRUE-VALUE
	PRINTI	" takes"
	ICALL	RT-PRINT-OBJ,OBJ,K-ART-THE
	PRINTI	" and gives you"
	ICALL	RT-PRINT-OBJ,ID,K-ART-THE
	PRINTC	46
	CRLF	
	BOR	GL-UPDATE-WINDOW,5 >GL-UPDATE-WINDOW
	EQUAL?	GL-WINDOW-TYPE,K-WIN-INVT \?CCL14
	ICALL1	RT-UPDATE-INVT-WINDOW
	RTRUE	
?CCL14:	EQUAL?	GL-WINDOW-TYPE,K-WIN-DESC \TRUE
	ICALL1	RT-UPDATE-DESC-WINDOW
	RTRUE	


	.FUNCT	RT-IDIOT-TAKE:ANY:1:1,OBJ,N
	MOVE	OBJ,CH-IDIOT
	FSET	OBJ,FL-NO-DESC
	GET	K-IDIOT-OBJ-TBL,0
	ADD	STACK,1 >N
	PUT	K-IDIOT-OBJ-TBL,0,N
	PUT	K-IDIOT-OBJ-TBL,N,OBJ
	RTRUE	


	.FUNCT	RT-IDIOT-GIVE:ANY:1:2,OBJ,PERSON,L,N,PTR
	ASSIGNED?	'PERSON /?CND1
	SET	'PERSON,CH-PLAYER
?CND1:	MOVE	OBJ,PERSON
	FCLEAR	OBJ,FL-NO-DESC
	GET	K-IDIOT-OBJ-TBL,0 >N
	INTBL?	OBJ,K-IDIOT-OBJ-TBL+2,N >PTR \FALSE
	SUB	K-IDIOT-OBJ-TBL+10,PTR >L
	GRTR?	L,0 \?CND6
	ADD	PTR,2
	COPYT	STACK,PTR,L
?CND6:	PUT	K-IDIOT-OBJ-TBL,K-IDIOT-OBJ-MAX,0
	SUB	N,1
	PUT	K-IDIOT-OBJ-TBL,0,STACK
	RTRUE	

	.ENDI
